services:

  db:
    image: postgres:18
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - postgres_logs:/var/log/postgresql
      - ./tools/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./tools/postgres/init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: tradironi-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - backend_logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 15s # check every 15s
      timeout: 5s # fail if no response in 5s
      retries: 5 # mark unhealthy after 5 consecutive failures
      start_period: 120s # give Spring Boot 60s to start before counting failures

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    ports:
      - "8180:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: /auth
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q '200'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

volumes:
  db_data:
  postgres_logs:
  backend_logs:
